### ISSUE TITLE
Animasia 3-D

### ISSUE THREAD

**Issue by xandark** [a2infinitum/apple2-filetypes#1]
Very cool to see this. I noticed in $C2 Paintworks Animation -> Compatible Software, there is an omission. Animasia 3-D was a latecomer to the scene, but it supported generation and playback of $C2's.

**Comment by digarok** [comment]
Addressed in https://github.com/a2infinitum/apple2-filetypes/pull/3

Thanks!  Closing, but feel free to reopen or file a new issue if you think something is still missing.
