### ISSUE TITLE
Animasia 3-D Project filetype

### ISSUE THREAD

**Issue by xandark** [a2infinitum/apple2-filetypes#2]
I registered a filetype with Apple in the 90's for Animasia 3-D. It's...

$C5/C008		Animasia 3-D Project

**Comment by digarok** [comment]
Thank you very much!  This is exactly why I put this on github.  Also, Animasia 3-D is awesome and I used to use it for the GSplus screenshots.  Thanks for the info.  Also, if you have any other supporting documentation (usenet posts, old reply from APDA or anything) that would be cool.  But this was definitely a real filetype so I'll add it ASAP.

**Comment by digarok** [comment]
Any info on the format specification would be lovely to have as well.

**Comment by digarok** [comment]
Addressed in https://github.com/a2infinitum/apple2-filetypes/pull/3

Thanks!  Closing, but feel free to reopen or file a new issue if you think something is still missing.

**Comment by xandark** [comment]
Thanks! I remember that I kept the paper email from Apple with the filetype information, but it's in storage in another state right now. I can't get that, but when I do, I'll try to remember to scan it and submit it for historical purposes.

As for documenting the file format, maybe someday, it's on my radar.
